version: '3.5'

services:
  db:
    container_name: order-manager-postgres
    image: postgres
    environment:
      - POSTGRES_DB=ordermanager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    container_name: order-manager-app
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8080:8080'
    volumes:
      - jacoco-data:/app/jacoco

  jacoco-server:
    container_name: jacoco-server
    image: nginx:alpine
    volumes:
      - jacoco-data:/usr/share/nginx/html/jacoco
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8000:80'

volumes:
  jacoco-data: