version: '3.5'

services:
  db:
    container_name: order-manager-postgres
    image: postgres
    environment:
      - POSTGRES_DB=ordermanager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    container_name: order-manager-app
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8080:8080'